version: '3'
services:
  flask-app:
    build: ./demo-app
    ports:
      - "5000:5000"
    container_name: flask-demo

  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins

